config/routes.rb
Rails.application.routes.draw do
  resources :games
  # get 'pages/home'
  root "pages#home"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "home#index"
  get "/about", to: "home#about"
end

app/models/game.rb
class Game < ApplicationRecord

  has_many :playables, dependent: :destroy
  has_many :sers, through: :playables

  enum state: {in_progress: 0, checkmate: 1, draw: 2}
  enum turns: {white: 0, black: 1}

  before_create :set_fen
  before_create :set_pgn

  def set_fen
    turn_abbreviation = if turn == 'white'
                          'w'
                        else
                          'b'
                        end

    self.fen = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR #{turn_abbreviation} KQkq - 0 1"
  end

  def set_pgn
    self.pgn =
          '
  [Event "Casual Game"]
  [Site "Localhost"]
  [Date "01/20/23"]
  [EventDate "?"]
  [Round "?"]
  [Result "1-0"]
  [White "?"]
  [Black "?"]
  [ECO "?"]
  [WhiteElo "?"]
  [BlackElo "?"]
  [PlyCount "?"]
  '
  end

  # used to rotate board for black player
  def orientation(user)
    if white_player_id == user.id
      'white'
    else
      'black'
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  include ColorConcerns

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    assign_colors
    @game = Game.new(turn: :white,
                     state: :in_progress,
                     white_player_id: params[:game][:white_player_id],
                     black_player_id: params[:game][:black_player_id])

    respond_to do |format|
      if @game.save
        Playable.create(game: @game, user_id: params[:game][:challenger_id])
        Playable.create(game: @game, user_id: params[:game][:challengee_id])
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(
        :color,
        :challenger_id,
        :challengee_id
    )
  end
end

app/views/games/_board.html.erb
<%= content_tag(:div, "", data: {
  controller: "chess",
  game_id: game.id,
  player_id: current_user.id,
  fen: game.fen,
  turn: game.turn[0],
  orientation: game.orientation(current_user)
}, style: "width: 400px") do %>
  <div id="board"></div>
  <strong>State:</strong>
  <%= content_tag(:div, "", data: {
    chess_target: "state"
  }) do %>
    <%= game.state %>
  <% end %>
  <%= content_tag(:div, "", data: {
    chess_target: "fen"
  }) do %>
    <%= game.fen %>
  <% end %>
<% end %>

app/views/games/_challenge_button.html.erb
<div class="container">
  <%= form_with model: Game.new, url: games_path, method: :post do |form| %>
    <div class="row form-group mb-5">
      <%= form.hidden_field :challenger_id, value: current_user.id %>
      <%= form.hidden_field :challengee_id, value: user.id %>
      <div class="col-4 p-0">
        <%= content_tag(:span, "#{user.email}", class:"input-group-text w-100") %>
      </div>
      <div class="col-4 p-0">
        <%= form.select :color,
                        options_for_select([['White', 'white'], ['Black', 'black'], ['Random', 'random']],
                                           ),{}, {class:"form-select w-100"} %>
      </div>
      <div class="col-4 p-0">
        <%= form.submit "Challenge", class:"btn btn-primary w-100" %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/_form.html.slim
= simple_form_for(@game) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :state
    = f.input :turn
    = f.input :fen
    = f.input :pgn
    = f.input :white_player_id
    = f.input :black_player_id

  .form-actions
    = f.button :submit

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <div class="row">
    <div class="col-8">
      <%= render partial: "games/board", locals: {game:game} %>
    </div>
    <div class="col-4">
      <%= render partial: "games/pgn", locals: {game:game} %>
    </div>
  </div>
</div>

app/views/games/_pgn.html.erb
<%= turbo_frame_tag dom_id(game, "pgn") do %>
  <h1>PGN</h1>
  <div>
    <pre class="pgn" id="<%= dom_id(game, "pre_pgn") %>"><%= game.pgn %></pre>
  </div>
<% end %>

app/views/games/edit.html.slim
h1 Editing game

== render "form", game: @game

br

div
  => link_to "Show this game", @game
  '|
  =< link_to "Back to games", games_path

app/views/games/index.html.slim
p style="color: green" = notice

h1 Games

#games
  - @games.each do |game|
    == render game
    p
      = link_to "Show this game", game

= link_to "New game", new_game_path

app/views/games/new.html.slim
h1 New game

== render "form", game: @game

br

div
  = link_to "Back to games", games_path

app/views/games/show.html.slim
p style="color: green" = notice

== render @game

div
  => link_to "Edit this game", edit_game_path(@game)
  '|
  =< link_to "Back to games", games_path

  = button_to "Destroy this game", @game, method: :delete