config/routes.rb
Rails.application.routes.draw do
  resources :games
  # get 'pages/home'
  root "pages#home"
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "home#index"
  get "/about", to: "home#about"
end

app/views/layouts/_players.html.erb
<% @users.each do |user| %>
  <% games = current_user.game_in_progress_with(user) %>
  <p>You are playing with <%= user.email %> <%= games.count %> games</p>
  <% games.each do |game| %>
    <%= link_to "Continue Game", game_path(game) %>
  <% end %>
  <%= render partial: "games/challenge_button", locals: { user: user }%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Video</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Video</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>
<body>
<div class="container">
  <section class="vh-100">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6 text-black">

          <div class="px-5 ms-xl-4 mt-4">
            <a href="https://github.com/RND-SOFT/">
              <img class="logo_rdns" src="https://avatars.githubusercontent.com/u/14114445?s=200&v=4" alt="Logo">
            </a>
            <span class="h1 fw-bold mb-0">Logo</span>
          </div>

          <div class="align-items-center px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
            <%= yield %>
          </div>
        </div>


        <div class="col-sm-6 px-0 d-none d-sm-block">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img3.webp"
               alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
        </div>
      </div>
    </div>

  </section>
</div>
</body>
</html>